# ============================================================================
# Step_03b: Export Seurat Object to MuData Format for Python
# ============================================================================
# This script converts the Seurat object from Step_040 to MuData (.h5mu) format
# so it can be used by the Python autoencoder script (Step_045).
#
# Input: Seurat RDS file from Step_040
# Output: MuData .h5mu file with RNA and ATAC modalities
#
# Usage:
#   Rscript 03b_export_to_mudata.R
# ============================================================================

# Get the directory of this script
get_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg))))
  }
  return(".")
}
script_dir <- get_script_dir()

# Source configuration file
config_path <- file.path(script_dir, "config_template.R")
if (!file.exists(config_path)) {
  config_path <- "config_template.R"
}

if (!file.exists(config_path)) {
  stop("config_template.R not found! Please ensure config_template.R is in the same directory as this script.")
}

cat("Loading configuration from:", config_path, "\n")
source(config_path)

# ============================================================================
# LOAD REQUIRED LIBRARIES
# ============================================================================
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(Matrix)
  library(reticulate)
})

# Try to use a Python environment with anndata and muon
# You may need to specify your conda environment name
tryCatch({
  use_condaenv("scvi-env", required = FALSE)
}, error = function(e) {
  message("Note: scvi-env not found, using default Python")
})

cat("\n")
cat("=", rep("=", 70), "\n", sep = "")
cat("STEP 040b: Export Seurat to MuData Format\n")
cat("=", rep("=", 70), "\n\n", sep = "")

# ============================================================================
# LOAD SEURAT OBJECT
# ============================================================================
cat("=== Loading Seurat object ===\n\n")

seurat_file <- file.path(
  OUTPUT_SPLITS_DIR, 
  paste0(SAMPLE_NAME, "_seurat_obj_with_splits.rds")
)

if (!file.exists(seurat_file)) {
  stop(sprintf("ERROR: Seurat file not found: %s\nPlease run Step_040 first.", seurat_file))
}

cat(sprintf("Loading: %s\n", seurat_file))
seurat_obj <- readRDS(seurat_file)

cat(sprintf("  Cells: %d\n", ncol(seurat_obj)))
cat(sprintf("  RNA features: %d\n", nrow(seurat_obj[["RNA"]])))
cat(sprintf("  ATAC features: %d\n", nrow(seurat_obj[["ATAC"]])))
cat(sprintf("  Data splits: %s\n", paste(table(seurat_obj$data_split), collapse = ", ")))

# ============================================================================
# EXPORT TO ANNDATA FORMAT (CSV FILES)
# ============================================================================
cat("\n=== Exporting to AnnData-compatible format ===\n\n")

# Create output directory
export_dir <- file.path(OUTPUT_SPLITS_DIR, "anndata_export")
if (!dir.exists(export_dir)) {
  dir.create(export_dir, recursive = TRUE)
}

# Export RNA counts matrix
cat("Exporting RNA count matrix...\n")
rna_counts <- GetAssayData(seurat_obj, assay = "RNA", layer = "counts")
writeMM(rna_counts, file.path(export_dir, "rna_counts.mtx"))
write.csv(colnames(rna_counts), file.path(export_dir, "cell_barcodes.csv"), row.names = FALSE)
write.csv(rownames(rna_counts), file.path(export_dir, "rna_features.csv"), row.names = FALSE)
cat(sprintf("  ✓ RNA matrix: %d genes × %d cells\n", nrow(rna_counts), ncol(rna_counts)))

# Export ATAC counts matrix
cat("Exporting ATAC count matrix...\n")
atac_counts <- GetAssayData(seurat_obj, assay = "ATAC", layer = "counts")
writeMM(atac_counts, file.path(export_dir, "atac_counts.mtx"))
write.csv(rownames(atac_counts), file.path(export_dir, "atac_features.csv"), row.names = FALSE)
cat(sprintf("  ✓ ATAC matrix: %d peaks × %d cells\n", nrow(atac_counts), ncol(atac_counts)))

# Export cell metadata
cat("Exporting cell metadata...\n")
cell_metadata <- seurat_obj@meta.data
write.csv(cell_metadata, file.path(export_dir, "cell_metadata.csv"), row.names = TRUE)
cat(sprintf("  ✓ Cell metadata: %d columns\n", ncol(cell_metadata)))

# ============================================================================
# CREATE PYTHON CONVERSION SCRIPT
# ============================================================================
cat("\n=== Creating Python conversion script ===\n\n")

python_script <- sprintf('#!/usr/bin/env python3
"""
Convert exported R matrices to MuData format for scvi-tools.
Auto-generated by Step_040b.Export_Seurat_To_MuData.R
"""
import os
import scipy.io
import pandas as pd
import numpy as np
import anndata as ad
import muon as mu

# Configuration
export_dir = "%s"
output_file = "%s"
sample_name = "%s"

print("=" * 80)
print("Converting R export to MuData format")
print("=" * 80)

# Load cell metadata
print("\\nLoading cell metadata...")
cell_metadata = pd.read_csv(os.path.join(export_dir, "cell_metadata.csv"), index_col=0)
print(f"  Cells: {len(cell_metadata)}")
print(f"  Columns: {list(cell_metadata.columns)}")

# Load cell barcodes
cell_barcodes = pd.read_csv(os.path.join(export_dir, "cell_barcodes.csv"))["x"].tolist()

# Load RNA data
print("\\nLoading RNA data...")
rna_counts = scipy.io.mmread(os.path.join(export_dir, "rna_counts.mtx")).T.tocsr()
rna_features = pd.read_csv(os.path.join(export_dir, "rna_features.csv"))["x"].tolist()
print(f"  RNA shape: {rna_counts.shape}")

# Create RNA AnnData
rna_adata = ad.AnnData(
    X=rna_counts,
    obs=cell_metadata.loc[cell_barcodes].copy(),
    var=pd.DataFrame(index=rna_features)
)
rna_adata.obs_names = cell_barcodes
rna_adata.var_names = rna_features

# Load ATAC data  
print("\\nLoading ATAC data...")
atac_counts = scipy.io.mmread(os.path.join(export_dir, "atac_counts.mtx")).T.tocsr()
atac_features = pd.read_csv(os.path.join(export_dir, "atac_features.csv"))["x"].tolist()
print(f"  ATAC shape: {atac_counts.shape}")

# Create ATAC AnnData
atac_adata = ad.AnnData(
    X=atac_counts,
    obs=cell_metadata.loc[cell_barcodes].copy(),
    var=pd.DataFrame(index=atac_features)
)
atac_adata.obs_names = cell_barcodes
atac_adata.var_names = atac_features

# Create MuData
print("\\nCreating MuData object...")
mdata = mu.MuData({"rna": rna_adata, "atac": atac_adata})
rna_nvars = mdata.mod["rna"].n_vars
atac_nvars = mdata.mod["atac"].n_vars
print(f"  MuData shape: {mdata.n_obs} cells, RNA: {rna_nvars}, ATAC: {atac_nvars}")

# Verify data_split column
if "data_split" in mdata.mod["rna"].obs.columns:
    print("\\nData split distribution:")
    print(mdata.mod["rna"].obs["data_split"].value_counts())
else:
    print("\\nWARNING: data_split column not found!")

# Save MuData
print(f"\\nSaving MuData to: {output_file}")
mdata.write(output_file)
print("✓ MuData file saved successfully!")

print("\\n" + "=" * 80)
print("Conversion complete!")
print("=" * 80)
print(f"\\nNext step: Run Step_045 with:")
print(f"  python Step_045.Dimensionality_Reduction_Autoencoders_Automated.py \\\\")
print(f"    --input {output_file} \\\\")
print(f"    --output-dir {os.path.dirname(output_file)}/autoencoder_latents \\\\")
print(f"    --sample-name {sample_name}")
', 
  path.expand(export_dir),
  file.path(path.expand(OUTPUT_SPLITS_DIR), paste0(SAMPLE_NAME, "_seurat_obj_with_splits_mu.h5mu")),
  SAMPLE_NAME
)

python_script_path <- file.path(export_dir, "convert_to_mudata.py")
writeLines(python_script, python_script_path)
cat(sprintf("Created: %s\n", python_script_path))

# ============================================================================
# TRY TO RUN PYTHON CONVERSION
# ============================================================================
cat("\n=== Running Python conversion ===\n\n")

# Check if Python dependencies are available
py_available <- tryCatch({
  py_module_available("anndata") && py_module_available("muon")
}, error = function(e) FALSE)

if (py_available) {
  cat("Python dependencies available. Running conversion...\n\n")
  tryCatch({
    source_python(python_script_path)
    cat("\n✓ MuData file created successfully!\n")
  }, error = function(e) {
    cat(sprintf("\n✗ Python conversion failed: %s\n", e$message))
    cat("\nPlease run manually:\n")
    cat(sprintf("  python %s\n", python_script_path))
  })
} else {
  cat("Python dependencies (anndata, muon) not available in R session.\n")
  cat("Please run the conversion script manually:\n\n")
  cat(sprintf("  conda activate scvi-env  # or your Python environment\n"))
  cat(sprintf("  python %s\n", python_script_path))
}

# ============================================================================
# COMPLETION MESSAGE
# ============================================================================
cat("\n")
cat("=", rep("=", 70), "\n", sep = "")
cat("STEP 03b COMPLETE\n")
cat("=", rep("=", 70), "\n\n", sep = "")

cat("Exported files:\n")
cat(sprintf("  - %s/rna_counts.mtx\n", export_dir))
cat(sprintf("  - %s/atac_counts.mtx\n", export_dir))
cat(sprintf("  - %s/cell_metadata.csv\n", export_dir))
cat(sprintf("  - %s/convert_to_mudata.py\n", export_dir))

cat("\nExpected MuData output:\n")
cat(sprintf("  - %s/%s_seurat_obj_with_splits_mu.h5mu\n", OUTPUT_SPLITS_DIR, SAMPLE_NAME))

cat("\nNext step: 03_metacell_creation_scvi_peakvi.R\n")
